// src/lib/icons.ts
// This is the single source of truth for all icons used in the application.
// It uses aliases for icons that might not have direct names in lucide-react
// to ensure the app compiles correctly and icons are consistent.

export {
  // === COMMON ACTIONS & UI ===
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  Bot,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronUp,
  ClipboardList,
  Clock,
  Cog,
  CreditCard,
  Download,
  Edit,
  Edit2Icon,
  Edit3,
  Euro,
  ExternalLink,
  Eye,
  EyeOff,
  FileEdit,
  FilePlus,
  FileText,
  Filter,
  Gavel,
  GitBranch,
  Globe,
  Handshake,
  HelpCircle,
  ImageIcon,
  ImageUp,
  Info,
  KeyRound,
  Lightbulb,
  List,
  ListChecks,
  Loader2,
  Lock,
  Menu,
  MessageSquarePlus,
  MessageSquareWarning,
  Mic,
  MoreVertical,
  MousePointerClick,
  Package,
  PauseCircle,
  Pencil,
  Percent,
  Phone,
  PlayCircle,
  Plus,
  PlusCircle,
  Power,
  Puzzle,
  RefreshCw,
  Repeat,
  Rocket,
  Save,
  Search,
  Send,
  Settings,
  Settings2,
  Share2,
  Shield,
  ShieldAlert,
  ShieldBan,
  Shuffle,
  Smile,
  Sparkles,
  Star,
  Stethoscope,
  Telescope,
  ThumbsUp,
  Timer,
  Trash,
  Trash2,
  Trophy,
  Upload,
  UserCircle,
  UserPlus,
  UserX,
  Video,
  Wallet,
  Wand2,
  Wrench,
  X,
  XCircle,
  Zap,

  // === DATA & CHARTS ===
  BarChart,
  TrendingDown,
  TrendingUp,
  PieChart,

  // === SOCIAL & BRANDS ===
  Facebook,
  Instagram,
  Linkedin,
  Twitter,
  
  // === CONTENT & USERS ===
  Archive,
  BookOpen,
  Brain,
  Briefcase,
  Contact,
  Copyright,
  Cpu,
  File,
  Folder,
  FolderOpen,
  Gamepad2,
  GraduationCap,
  Heart,
  Home,
  Languages,
  LayoutDashboard,
  Mail,
  MessageCircle,
  MessageSquare,
  NotebookPen,
  NotebookText,
  User,
  Users,
  
  // === TIME & CALENDAR ===
  Calendar,
  FileClock,
  History,
  Hourglass,
  
  // === NATURE & MISC ===
  Compass,
  DollarSign,
  Fingerprint,
  FlaskConical,
  Gauge,
  MapPin,
  Moon,
  Navigation,
  Sun,
  SunMedium,
  Waves,
  Link2Off,

  // === ALIASES FOR CONSISTENCY & FALLBACKS ===
  BarChart as BarChart3,
  BarChart as BarChartHorizontal,
  FileText as FileBarChart,
  FileText as FileTextIcon,
  
  BookOpen as BookHeart,
  BookOpen as BookOpenCheck,
  BookOpen as BookUser,
  
  Calendar as CalendarClock,
  Calendar as CalendarDays,
  Calendar as CalendarPlus,
  
  CheckCircle as CheckCircle2,
  Clock as ClockIcon,
  
  ExternalLink as Link2,
  Link as LinkIcon,
  
  Handshake as HeartHandshake,
  
  MessageSquare as MessageCircleQuestion,
  MessageSquare as MessagesSquare,
  MessageSquare as MessageSquareText,
  
  Menu as PanelLeft,
  Power as LogOut,
  PlusCircle as PlusCircleIcon,
  
  Save as SaveIcon,
  School,
  ScrollText,

  Shield as ShieldCheck,
  Circle as Target,
  User as UserCheck,
  Users as UsersIcon,
  Users as UsersIconLucide,
} from 'lucide-react';
