
// src/lib/icons.ts
// This is the single source of truth for all icons used in the application.
// It uses aliases for icons that might not have direct names in lucide-react
// to ensure the app compiles correctly and icons are consistent.

export {
  Activity,
  AlertCircle,
  AlertTriangle,
  Archive,
  ArrowLeft,
  ArrowRight,
  BarChart,
  BarChart as BarChartHorizontal,
  BookHeart,
  BookOpen,
  BookOpen as BookOpenCheck,
  BookOpen as BookUser,
  Bot,
  Brain,
  Briefcase,
  Calendar,
  Calendar as CalendarClock,
  Calendar as CalendarDays,
  Calendar as CalendarPlus,
  Check,
  CheckCircle,
  CheckCircle as CheckCircle2,
  CheckSquare,
  ChevronDown,
  ChevronUp,
  Circle,
  ClipboardList,
  Clock,
  Clock as ClockIcon,
  Cog,
  Compass,
  Contact,
  Copyright,
  Cookie,
  Cpu,
  CreditCard,
  Database,
  Download,
  Edit,
  Edit2Icon,
  Edit3,
  Euro,
  ExternalLink,
  ExternalLink as Link2,
  Eye,
  EyeOff,
  Facebook,
  FileEdit,
  FilePlus,
  FileText,
  FileText as FileBarChart,
  FileClock,
  Filter,
  Fingerprint,
  FlaskConical,
  Folder,
  FolderOpen,
  Gamepad2,
  Gavel,
  GitBranch,
  Globe,
  GraduationCap,
  Gauge,
  Handshake,
  Handshake as HeartHandshake,
  Heart,
  HelpCircle,
  Home,
  Hourglass,
  ImageUp,
  Info,
  Instagram,
  KeyRound,
  Languages,
  LayoutDashboard,
  Lightbulb,
  Link as LinkIcon,
  Link2Off,
  Linkedin,
  List,
  ListChecks,
  Loader2,
  Lock,
  Mail,
  MapPin,
  Menu,
  Menu as PanelLeft,
  MessageCircle,
  MessageCircle as MessageCircleQuestion,
  MessageSquare,
  MessageSquare as MessagesSquare,
  MessageSquare as MessageSquarePlus,
  MessageSquare as MessageSquareText,
  MessageSquareWarning,
  Mic,
  Moon,
  MoreVertical,
  MousePointerClick,
  Navigation,
  NotebookPen,
  Package,
  PauseCircle,
  Pencil,
  Percent,
  Phone,
  PieChart,
  PlayCircle,
  Power,
  Power as LogOut,
  Puzzle,
  RefreshCw,
  Repeat,
  Rocket,
  Save,
  Save as SaveIcon,
  School,
  ScrollText,
  Search,
  Send,
  Separator,
  Settings,
  Settings2,
  Share2,
  Shield,
  Shield as ShieldCheck,
  ShieldAlert,
  ShieldBan,
  ShoppingBag,
  ShoppingCart,
  Shuffle,
  Siren,
  Smile,
  Sparkles,
  Star,
  Stethoscope,
  Sun,
  SunMedium,
  Circle as Target,
  Telescope,
  ThumbsUp,
  Timer,
  Trash,
  Trash2,
  TrendingDown,
  TrendingUp,
  Trophy,
  Twitter,
  Upload,
  User,
  User as UserCheck,
  UserCircle,
  UserPlus,
  UserX,
  Users,
  Users as UsersIcon,
  Users as UsersIconLucide,
  Video,
  Wallet,
  Wand2,
  Waves,
  Wrench,
  X,
  XCircle,
  Zap,
} from 'lucide-react';
