// src/lib/quiz-data/seed-quizzes.ts
import type { QuizAdmin } from '@/types/quiz-admin';

export const LOCAL_STORAGE_QUIZ_SEEDED_KEY = 'mindnavigator_quizzes_seeded_v1';

export const SEED_QUIZZES_DATA: QuizAdmin[] = [
  {
    id: 'teen-neuro-12-14',
    title: 'Zelfreflectie Tool (12-14 jr)',
    slug: 'zelfreflectie-tool-12-14',
    description: 'Start hier om jouw unieke eigenschappen en denkstijl te verkennen. Dit helpt ons om je de beste vervolgstappen te tonen.',
    audience: ['Tiener (12-14 jr, voor zichzelf)'],
    category: 'Basis',
    status: 'published',
    questions: [
        { id: 'q1', text: 'Dwalen je gedachten makkelijk af als je je probeert te concentreren, bijvoorbeeld op school?', weight: 1 },
        { id: 'q2', text: 'Moet je dingen vaak opnieuw lezen omdat je niet goed oplette?', weight: 1 },
        { id: 'q3', text: 'Als je stil moet zitten, bijvoorbeeld in de klas, voel je je dan vaak onrustig?', weight: 1 },
        { id: 'q4', text: 'Flap je er wel eens antwoorden uit voordat je aan de beurt bent?', weight: 1 },
    ],
    lastUpdatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    thumbnailUrl: 'https://firebasestorage.googleapis.com/v0/b/neurodiversity-navigator.firebasestorage.app/o/young_teenage_boy_13_years_old_with_blonde_hair.png?alt=media&token=79e72caf-3dcd-4dcf-8d01-9074ceb3f8aa',
  },
  {
    id: 'teen-neuro-15-18',
    title: 'Zelfreflectie Tool (15-18 jr)',
    slug: 'zelfreflectie-tool-15-18',
    description: 'Start hier om jouw unieke eigenschappen en denkstijl te verkennen. Dit helpt ons om je de beste vervolgstappen te tonen.',
    audience: ['Tiener (15-18 jr, voor zichzelf)'],
    category: 'Basis',
    status: 'published',
    questions: [
        { id: 'q1', text: 'Ik merk dat mijn gedachten afdwalen, zelfs als ik probeer te focussen op schoolwerk.', weight: 1 },
        { id: 'q2', text: 'Ik moet bladzijdes of opdrachten vaak opnieuw lezen omdat ik niet oplet wat ik lees.', weight: 1 },
        { id: 'q3', text: 'Kleine afleidingen zoals tikkende pennen of pratende klasgenoten verstoren mijn concentratie volledig.', weight: 1 },
        { id: 'q4', text: 'Ik voel me onrustig als ik lang stil moet zitten in de klas.', weight: 1 },
    ],
    lastUpdatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    thumbnailUrl: 'https://firebasestorage.googleapis.com/v0/b/neurodiversity-navigator.firebasestorage.app/o/teenage_girl_with_dark_hair_in_ponytai.png?alt=media&token=055da5d1-2291-4858-8c90-b903be950264',
  },
  {
    id: 'exam-stress-planning',
    title: 'Omgaan met Examenvrees',
    slug: 'omgaan-met-examenvrees',
    description: 'Leer stress te beheersen en je planning scherp te houden.',
    audience: ['Tiener (12-14 jr, voor zichzelf)', 'Tiener (15-18 jr, voor zichzelf)', 'Algemeen (alle leeftijden, voor zichzelf)'],
    category: 'Thema',
    status: 'published',
    questions: [
        { id: 'q1', text: 'Maak je je vaak zorgen over een toets, ook al heb je goed geleerd?', weight: 1 },
        { id: 'q2', text: 'Vind je het moeilijk om te beginnen met leren voor een examen?', weight: 1 },
    ],
    lastUpdatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    thumbnailUrl: 'https://firebasestorage.googleapis.com/v0/b/neurodiversity-navigator.firebasestorage.app/o/teenage_girl_with_dark_skin_curly_hair.png?alt=media&token=00582d3b-19c5-4744-be12-8636535829f8',
  },
  {
    id: 'social-anxiety-friendships',
    title: 'Sociale Situaties & Vriendschap',
    slug: 'sociale-situaties-vriendschap',
    description: 'Verken hoe je je voelt in groepen en bij presentaties.',
    audience: ['Tiener (12-14 jr, voor zichzelf)', 'Tiener (15-18 jr, voor zichzelf)', 'Algemeen (alle leeftijden, voor zichzelf)'],
    category: 'Thema',
    status: 'published',
    questions: [
        { id: 'q1', text: 'Vind je het spannend om nieuwe mensen te ontmoeten?', weight: 1 },
        { id: 'q2', text: 'Denk je veel na over wat anderen van je denken in een groep?', weight: 1 },
    ],
    lastUpdatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    thumbnailUrl: 'https://firebasestorage.googleapis.com/v0/b/neurodiversity-navigator.firebasestorage.app/o/mixed-race_Asian_teenage_boy_with_Chinese_features.png?alt=media&token=09c31095-7bea-4206-9254-7e65c46ea5ec',
  },
  {
    id: 'focus-digital-distraction',
    title: 'Focus & Digitale Afleiding Tool',
    slug: 'focus-digitale-afleiding',
    description: 'Verken je aandachtspatronen in relatie tot digitale media.',
    audience: ['Tiener (12-14 jr, voor zichzelf)', 'Tiener (15-18 jr, voor zichzelf)', 'Algemeen (alle leeftijden, voor zichzelf)'],
    category: 'Thema',
    status: 'published',
    questions: [
        { id: 'q1', text: 'Raak je makkelijk afgeleid door meldingen op je telefoon tijdens het huiswerk?', weight: 1 },
        { id: 'q2', text: 'Merk je dat je langer op social media zit dan je van plan was?', weight: 1 },
    ],
    lastUpdatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    thumbnailUrl: 'https://firebasestorage.googleapis.com/v0/b/neurodiversity-navigator.firebasestorage.app/o/teenage_girl_with_dark_hair_in_ponytail-screen-time.png?alt=media&token=17820a6c-b5ad-4719-ac21-6541d59ada65',
  },
  {
    id: 'motivation-goals',
    title: 'Motivatie & Doelen Stellen',
    slug: 'motivatie-doelen-stellen',
    description: 'Leer doelen stellen, successen vieren en gemotiveerd te blijven.',
    audience: ['Tiener (12-14 jr, voor zichzelf)', 'Tiener (15-18 jr, voor zichzelf)', 'Algemeen (alle leeftijden, voor zichzelf)'],
    category: 'Thema',
    status: 'published',
    questions: [
        { id: 'q1', text: 'Vind je het moeilijk om gemotiveerd te blijven voor schoolwerk dat je niet interessant vindt?', weight: 1 },
        { id: 'q2', text: 'Stel je soms doelen voor jezelf, zoals het leren van een nieuw liedje of het lezen van een boek?', weight: 1 },
    ],
    lastUpdatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    thumbnailUrl: 'https://firebasestorage.googleapis.com/v0/b/neurodiversity-navigator.firebasestorage.app/o/teenage_boy_with_dark_skin_setting_goals_and_celeb.png?alt=media&token=91f4d153-37f2-468f-a40e-4a6606ba1670',
  },
];
